# Generated by Django 4.2.6 on 2023-11-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_rename_image_employees_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='images',
            new_name='profile_pic',
        ),
    ]
